services:
  node:
    image: node-docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-lts}
    hostname: node-js
    platform: linux/amd64
    ports:
      - "${PORT_HOST:-9001}:${PORT_CONTAINER:-9001}"
    volumes:
      - ./proyectos:/proyectos
      - node_data:/home/node
      - root_data:/root
      - local_data:/usr/local

volumes:
  node_data:
  root_data:
  local_data:
