services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-lts}
    hostname: node-js
    platform: linux/amd64
    volumes:
      - ./proyectos:/proyectos
      - node_data:/home/node
      - root_data:/root

volumes:
  node_data:
  root_data:
